### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by KaKi87** [the-machine-project/the-machine-web#2]
Please can you tell me how do we use it ?

Thanks.

**Comment by Xalaxis** [comment]
The website is simply a website, nothing more.  What specifically do you want to use?

**Comment by KaKi87** [comment]
Wow, very fast answer. Does that means the project is alive ?

I want to open the website but I don't see index.html, that's why I'm asking that.

Thanks.

**Comment by kodbilenadam** [comment]
Website is only for introduction of the project. Main project can be found under https://github.com/the-machine-project/the-machine

**Comment by KaKi87** [comment]
So what is the difference between the-machine-web (The Machine Project - Web version) and the-machine-website (The Machine's website) ? Thanks.

**Comment by kodbilenadam** [comment]
The Machine Project - Web version was under develop and never published. We had some ideas about it but then we stopped doing that ideas.

**Comment by Xalaxis** [comment]
To clarify:
The Machine Web version was designed to be an in-browser representation of the machine, probably running via a combination of JavaScript and HTML5
The Machine website is simply the website files for the homepage we used to have up
